<?php

namespace AppBundle\Repository;

/**
 * PassageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassageRepository extends \Doctrine\ORM\EntityRepository
{
}
